Put it"

diff --git a/put-in b/put-in
--- a/put-in
+++ b/put-in
@@ -3,6 +3,13 @@
 set -ex
 
 src="${1}"
+
+if [ ! -f "${src}" ]
+then
+  echo "File not found: ${src}" >&2
+  exit 1
+fi
+
 dest=$(echo "${1}" | sed -e "s|${HOME}/*||" -e "s/^[.]/dot-/")
 destdir=$(echo "${dest}" | sed -e 's|/[^/]*$||')
 
diff --git a/take-out b/take-out
--- a/take-out
+++ b/take-out
@@ -3,6 +3,14 @@
 set -ex
 
 src="${1}"
+
+if [ ! -f "${src}" ]
+then
+    echo "File not found: ${src}" >&2
+    exit 1
+fi
+
+
 dest=$(echo "${1}" | sed -e "s/^dot-/./" -e "s|^|${HOME}/|")
 destdir=$(echo "${dest}" | sed -e 's|/[^/]*$||')
 
